[package]
name = "overhop"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.140"
signal-hook = "0.3.18"
toml = "0.8.23"
